before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - DB=sqlite
# command to run tests
script: nosetests --with-coverage

after_success:
  - coveralls
